apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: serverboiz-image-updater
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "serverboizbot"
      images:
        - alias: "serverboizbot"
          imageName: "ghcr.io/viyi/serverboizbot"
          commonUpdateSettings:
            updateStrategy: newest-build